### ISSUE TITLE
No controls defined when running locally 

### ISSUE THREAD

**Issue by rafaelcorsi** [wokwi/inverter-chip#1]
I get this error when running this example locally with devcontainer and click on `inverter` while simulating 

![image](https://github.com/wokwi/inverter-chip/assets/1039615/a05ab94f-cc16-4b10-9b25-2bd2a6939576)

**Comment by urish** [comment]
Hi Rafael, the inverter does not define any controls, so this is an expected behavior.

**Comment by rafaelcorsi** [comment]
ok thanks.  Maybe not showing anything would be better,  the message looks like an error not an absence of features.
